import { Lead, Client, PipelineStage } from './types';

export const MOCK_LEADS: Lead[] = [
  {
    id: 'L001',
    contactName: 'Sarah Johnson',
    company: 'TechFlow Solutions',
    source: 'LinkedIn',
    serviceType: 'Consulting',
    urgency: 'High',
    channel: 'Direct',
    value: 15000,
    stage: PipelineStage.NEGOTIATION,
    expectedCloseDate: '2023-11-15',
    createdAt: '2023-10-01',
    assignedTo: {
      id: 'u1',
      name: 'Alex Sales',
      email: 'alex@example.com',
      role: 'SALES',
    },
    uploads: [
      {
        id: 'f1',
        name: 'Requirements.pdf',
        url: '#',
        uploadedAt: '2023-10-01',
      },
    ],
    activities: [
      {
        id: 'a1',
        type: 'call',
        content: 'Introductory call regarding cloud migration.',
        timestamp: '2023-10-02T10:00:00',
        user: 'Alex Sales',
      },
      {
        id: 'a2',
        type: 'status_change',
        content: 'Moved to Negotiation',
        timestamp: '2023-10-20T14:30:00',
        user: 'Alex Sales',
      },
    ],
  },
  {
    id: 'L002',
    contactName: 'Michael Chen',
    company: 'GreenEarth Logistics',
    source: 'Website',
    serviceType: 'Audit',
    urgency: 'Medium',
    channel: 'Web Form',
    value: 8500,
    stage: PipelineStage.PROPOSAL,
    expectedCloseDate: '2023-11-20',
    createdAt: '2023-10-10',
    assignedTo: {
      id: 'u2',
      name: 'Maria Manager',
      email: 'maria@example.com',
      role: 'MANAGER',
    },
    uploads: [],
    activities: [
      {
        id: 'a3',
        type: 'note',
        content: 'Sent preliminary proposal.',
        timestamp: '2023-10-12T09:15:00',
        user: 'Maria Manager',
      },
    ],
  },
  {
    id: 'L003',
    contactName: 'David Smith',
    company: 'Apex Retail',
    source: 'Referral',
    serviceType: 'Implementation',
    urgency: 'Low',
    channel: 'Email',
    value: 45000,
    stage: PipelineStage.NEW,
    expectedCloseDate: '2023-12-01',
    createdAt: '2023-10-25',
    assignedTo: {
      id: 'u1',
      name: 'Alex Sales',
      email: 'alex@example.com',
      role: 'SALES',
    },
    uploads: [],
    activities: [],
  },
  {
    id: 'L004',
    contactName: 'Emily Davis',
    company: 'Innovate Corp',
    source: 'Event',
    serviceType: 'Training',
    urgency: 'High',
    channel: 'In Person',
    value: 12000,
    stage: PipelineStage.WON,
    expectedCloseDate: '2023-10-15',
    createdAt: '2023-09-15',
    assignedTo: {
      id: 'u2',
      name: 'Maria Manager',
      email: 'maria@example.com',
      role: 'MANAGER',
    },
    uploads: [
      {
        id: 'f2',
        name: 'Signed_Contract.pdf',
        url: '#',
        uploadedAt: '2023-10-15',
      },
    ],
    activities: [
      {
        id: 'a4',
        type: 'status_change',
        content: 'Deal Closed',
        timestamp: '2023-10-15T16:00:00',
        user: 'Maria Manager',
      },
    ],
  },
  {
    id: 'L005',
    contactName: 'Robert Wilson',
    company: 'Construct Co',
    source: 'Cold Call',
    serviceType: 'Consulting',
    urgency: 'Medium',
    channel: 'Phone',
    value: 22000,
    stage: PipelineStage.CONTACTED,
    expectedCloseDate: '2023-11-30',
    createdAt: '2023-10-18',
    assignedTo: {
      id: 'u1',
      name: 'Alex Sales',
      email: 'alex@example.com',
      role: 'SALES',
    },
    uploads: [],
    activities: [],
  },
];

export const MOCK_CLIENTS: Client[] = [
  {
    id: 'C001',
    name: 'Acme Industries',
    segment: 'Multinational',
    industry: 'Manufacturing',
    accountManager: {
      id: 'u2',
      name: 'Maria Manager',
      email: 'maria@example.com',
      role: 'MANAGER',
    },
    lifetimeRevenue: 150000,
    status: 'Active',
    lastInteraction: '2023-10-24',
    projects: [
      {
        id: 'P-101',
        name: 'Cloud Migration Phase 1',
        status: 'Active',
        value: 75000,
      },
      {
        id: 'P-102',
        name: 'Cloud Migration Phase 2',
        status: 'Planning',
        value: 75000,
      },
    ],
    uploads: [
      {
        id: 'cf1',
        name: 'MSA_2023.pdf',
        url: '#',
        uploadedAt: '2023-01-15',
      },
    ],
  },
  {
    id: 'C002',
    name: 'Beta Startups',
    segment: 'SME',
    industry: 'Technology',
    accountManager: {
      id: 'u1',
      name: 'Alex Sales',
      email: 'alex@example.com',
      role: 'SALES',
    },
    lifetimeRevenue: 25000,
    status: 'At Risk',
    lastInteraction: '2023-09-10',
    projects: [
      {
        id: 'P-201',
        name: 'Web App Development',
        status: 'Active',
        value: 25000,
      },
    ],
    uploads: [],
  },
  {
    id: 'C003',
    name: 'Gamma Global',
    segment: 'Corporate',
    industry: 'Finance',
    accountManager: {
      id: 'u2',
      name: 'Maria Manager',
      email: 'maria@example.com',
      role: 'MANAGER',
    },
    lifetimeRevenue: 89000,
    status: 'Active',
    lastInteraction: '2023-10-20',
    projects: [
      {
        id: 'P-301',
        name: 'Financial System Upgrade',
        status: 'Completed',
        value: 40000,
      },
      {
        id: 'P-302',
        name: 'Security Audit',
        status: 'Active',
        value: 25000,
      },
      {
        id: 'P-303',
        name: 'Compliance Consulting',
        status: 'Planning',
        value: 24000,
      },
    ],
    uploads: [],
  },
];

export const REVENUE_DATA = [
  { name: 'Jan', revenue: 40000 },
  { name: 'Feb', revenue: 30000 },
  { name: 'Mar', revenue: 55000 },
  { name: 'Apr', revenue: 45000 },
  { name: 'May', revenue: 60000 },
  { name: 'Jun', revenue: 75000 },
];

export const PIPELINE_DATA = [
  { name: 'New', value: 5 },
  { name: 'Contacted', value: 8 },
  { name: 'Quoted', value: 4 },
  { name: 'Negotiation', value: 3 },
  { name: 'Won', value: 12 },
];
